version: '3'
services:

   mongodb1:
     image: ksravikumar2005/mongodb:latest
     hostname: mongodb1
     ports:
       - 27017:27017
     volumes:
       - mongodb1_datadb:/data/db
     networks:
       - mongodb

   mongodb2:
     image: ksravikumar2005/mongodb:latest
     hostname: mongodb2
     ports:
       - 37017:27017
     volumes:
       - mongodb2_datadb:/data/db
     networks:
       - mongodb
volumes:
   mongodb1_datadb:
   mongodb2_datadb:
networks:
  mongodb:

