version: '3'
services:

   mongodb1:
     image: ksravikumar2005/mongodb:latest
     hostname: mongodb1
     ports:
       - 27017:27017
     volumes:
       - mongodb1_datadb:/data/db
     networks:
       - mongodb
     environment:
       MONGO_INITDB_ROOT_USERNAME: adminUser
       MONGO_INITDB_ROOT_PASSWORD: adminPass@123

   mongodb2:
     image: ksravikumar2005/mongodb:latest
     hostname: mongodb2
     ports:
       - 37017:27017
     volumes:
       - mongodb2_datadb:/data/db
     networks:
       - mongodb
volumes:
   mongodb1_datadb:
   mongodb2_datadb:
networks:
  mongodb:

